### ISSUE TITLE
no notification handler registered.

### ISSUE THREAD

**Issue by Innei** [ObserverOfTime/discord.nvim#2] opened 2020-02-20 09:28 UTC
When I open nvim, then show this error.

```
no notification handler registered for "/Users/innei/.config/nvim/plugged/discord.nvim/rpl
ugin/python3/discord:autocmd:VimEnter:*"
Press ENTER or type command to continue
```
this is my nvim config.

```
Plug 'ObserverOfTime/discord.nvim', {'do': ':UpdateRemotePlugins'}
```

then I do `UpdateRemotePlugins`

```
remote/host: python3 host registered plugins ['discord', 'fzf_gitignore.py']
remote/host: generated rplugin manifest: /Users/innei/.local/share/nvim/rplugin.vim
Press ENTER or type command to continue
```

Platform:  OS X 10.15.2
Python: Python 3.7.3

```
health#discord#check
    3 ========================================================================
    4 ## discord.nvim
    5   - OK: has("nvim") was successful
    6   - OK: has("timers") was successful
    7   - OK: has("python3") was successful
    8   - INFO: If you are still having problems, create an issue on https://github.com/aurieh/discord.nvim/issues
```

**Comment by ObserverOfTime** [comment] 2020-02-20 10:01
Duplicate of #1

**Closed as completed** 2020-02-20 10:01 UTC
Labels: duplicate

**Comment by Innei** [comment] 2020-02-20 10:41
Still error, when I change branch to refactoyed.

**Comment by ObserverOfTime** [comment] 2020-02-20 11:15
Well, yeah... That doesn't change anything.

**Comment by Innei** [comment] 2020-02-20 11:23
But the error increased to two, one before

**Comment by ObserverOfTime** [comment] 2020-02-20 11:24
If you want to learn more about this issue, follow the links in aurieh#22.

**Comment by Innei** [comment] 2020-02-20 11:32
Uh,I used `aurieh/discord.nvim` before, but there were no errors. Then I try to replace `ObserverOfTime/discord.nvim`, but cause this error. I saw the PR to fix this bug..

**Comment by Innei** [comment] 2020-02-20 11:44
`rplugins.vim` is also correct.

```vim
" python3 plugins
call remote#host#RegisterPlugin('python3', '/Users/innei/.config/nvim/plugged/discord.nvim/rplugin/python3/discord', [
      \ {'sync': v:false, 'name': 'DiscordListFiletypes', 'type': 'command', 'opts': {'nargs': '?'}},
      \ {'sync': v:true, 'name': 'BufEnter', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:true, 'name': 'VimEnter', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': '_DiscordRunScheduled', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'DiscordUpdatePresence', 'type': 'command', 'opts': {'bang': ''}},
     \ ])
```

**Comment by ObserverOfTime** [comment] 2020-02-20 11:45
The same bugfix is available here.

https://github.com/ObserverOfTime/discord.nvim/blob/9f5430b175d9571910c72f46729b80f202670b09/rplugin/python3/discord/__init__.py#L44-L46
https://github.com/ObserverOfTime/discord.nvim/blob/9f5430b175d9571910c72f46729b80f202670b09/rplugin/python3/discord/__init__.py#L53-L55

This issue is, as far as we know, caused by random race conditions.

**Comment by Innei** [comment] 2020-02-20 11:47
I found the solution, just remove the `rplugins.vim`, and `:UpdateRemotePlugins` again.

It worked.

**Comment by Innei** [comment] 2020-02-20 12:10
But now, a new error caused. Only in branch `refactored`
```
[Discord] [Errno 3] No such process
```

**Comment by ObserverOfTime** [comment] 2020-02-20 12:13
Open a new issue for that.
